#include "Node.h"
#include "NodeArray.h"
#include "NodeBracketExp2.h"
#include "NodeDecl.h"
#include "NodeDecls.h"
#include "NodeEpsilon.h"
#include "NodeExp.h"
#include "NodeExp2.h"
#include "NodeExp2Exclamation.h"
#include "NodeExp2Identifier.h"
#include "NodeExp2Integer.h"
#include "NodeExp2Minus.h"
#include "NodeIdentifier.h"
#include "NodeIndex.h"
#include "NodeInteger.h"
#include "NodeOp.h"
#include "NodeOpExp.h"
#include "NodeProg.h"
#include "NodeStatement.h"
#include "NodeStatementAssign.h"
#include "NodeStatementBlock.h"
#include "NodeStatementIf.h"
#include "NodeStatementRead.h"
#include "NodeStatements.h"
#include "NodeStatementWhile.h"
#include "NodeStatementWrite.h"

class VisitorTypeCheck : Visitor{
    //
};